services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: car-platform-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: car_user
      RABBITMQ_DEFAULT_PASS: car_password
      RABBITMQ_DEFAULT_VHOST: car_platform

    ports:
      - '5672:5672'
      - '15672:15672'

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

    networks:
      - car-platform-network

  postgres:
    image: postgres:17
    container_name: car-platform-postgres
    hostname: postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_password
      POSTGRES_DB: car_service_db

    ports:
      - '5432:5432'

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U car_user -d car_service_db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - car-platform-network

  keycloak-postgres:
    image: postgres:17
    container_name: car-platform-keycloak-postgres
    hostname: keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U keycloak -d keycloak']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - car-platform-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.6.3 
    container_name: car-platform-keycloak
    hostname: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak_password

      KC_HEALTH_ENABLED: 'true'
    ports:
      - '8080:8080'
    depends_on:
      keycloak-postgres:
        condition: service_healthy
    networks:
      - car-platform-network

  mailpit:
    image: axllent/mailpit:latest
    container_name: car-platform-mailpit
    hostname: mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - car-platform-network

volumes:
  rabbitmq_data:
  postgres_data:
  keycloak_postgres_data:

networks:
  car-platform-network:
    driver: bridge
