_format_version: '3.0'

services:
  - name: api-gateway
    url: http://host.docker.internal:3000

    routes:
      - name: api
        paths:
          - /api
        strip_path: true

        plugins:

          - name: rate-limiting

            config:
              minute: 10
              policy: local
              hide_client_headers: false

          - name: correlation-id

            config:
              header_name: X-Request-ID
              generator: uuid
              echo_downstream: true

          - name: cors

            config:
              origins:
                - http://localhost:3000

              methods:
                - GET
                - POST
                - PATCH
                - DELETE

              headers:
                - Authorization
                - Content-Type

              exposed_headers:
                - X-Request-ID
              credentials: true

plugins: []
